# Generated by Django 3.2.9 on 2022-02-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211225_1325'),
        ('authapp', '0004_userprofile_langs'),
    ]

    operations = [
    ]
