# Generated by Django 3.2.9 on 2022-01-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-create_at',), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
